In [1]:
import torch
from d2l import torch as d2l

In [4]:
def corr2d_multi_in(X, K):
    # 先遍历“X”和“K”的第0个维度（通道维度），再把它们加在一起
    return sum(d2l.corr2d(x,k) for x, k in zip(X,K))

In [11]:
X = torch.tensor([
                    [
                     [0.0, 1.0, 2.0], 
                     [3.0, 4.0, 5.0], 
                     [6.0, 7.0, 8.0]
                    ],
                    [
                     [1.0, 2.0, 3.0], 
                     [4.0, 5.0, 6.0], 
                     [7.0, 8.0, 9.0]
                    ]
                ])
K = torch.tensor([
                    [[0.0, 1.0], [2.0, 3.0]], 
                    [[1.0, 2.0], [3.0, 4.0]]
                ])
corr2d_multi_in(X, K)

tensor([[ 56.,  72.],
        [104., 120.]])

In [6]:
for x, k in zip(X,K):
    print(d2l.corr2d(x,k))

tensor([[19., 25.],
        [37., 43.]])
tensor([[37., 47.],
        [67., 77.]])


### 多输出通道 

In [12]:
K = torch.stack((K, K + 1, K + 2), 0)
K.shape

torch.Size([3, 2, 2, 2])

In [13]:
def corr2d_multi_in_out(X, K):
    # 迭代“K”的第0个维度，每次都对输入“X”执行互相关运算。
    # 最后将所有结果都叠加在一起
    return torch.stack([corr2d_multi_in(X, k) for k in K], 0)

In [14]:
for k in K:
    print(k)

tensor([[[0., 1.],
         [2., 3.]],

        [[1., 2.],
         [3., 4.]]])
tensor([[[1., 2.],
         [3., 4.]],

        [[2., 3.],
         [4., 5.]]])
tensor([[[2., 3.],
         [4., 5.]],

        [[3., 4.],
         [5., 6.]]])
