### 5.4.1 不带参数的层 

In [1]:
import torch
import torch.nn.functional as F
from torch import nn
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, X):
        return X - X.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.rand(4, 8))
Y.mean()

tensor(3.4925e-09, grad_fn=<MeanBackward0>)

### 5.4.2 带参数的层 

In [5]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [6]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-1.2178, -1.4731, -1.2203],
        [ 1.2673, -0.7535,  2.4631],
        [ 0.0731, -0.2582,  0.9946],
        [ 0.9831,  1.1449, -0.5525],
        [ 0.0509, -0.5299,  0.2474]], requires_grad=True)

In [7]:
linear(torch.rand(2, 5))

tensor([[0.0000, 0.0000, 1.2404],
        [0.1343, 0.3154, 2.4621]])

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))


tensor([[ 1.5399],
        [11.9856]])