In [2]:
import torch

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
# 访问张量的形状
x.shape

torch.Size([12])

In [5]:
# 张量中元素的总数
x.numel()

12

In [6]:
# 改变张量的形状，而不改变元素数量和元素值
X = x.reshape(3, 4)
# 若想获取三行的
X = x.reshape(3, -1)
# 若想获取四列的
X = x.reshape(-1, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
#全零常量
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
#全一常量
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
# 从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样
torch.randn(3, 4)

tensor([[-1.0382e-03, -4.3198e-01, -8.2726e-02, -7.9434e-03],
        [ 6.1315e-01,  8.7408e-02,  6.0505e-01, -1.4809e-01],
        [-8.6514e-01, -1.5712e+00,  1.5052e+00, -1.0909e-01]])

In [10]:
# 通过嵌套列表来确定
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])


tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [11]:
#计算
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x-y, x*y, x/y, x**y
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [12]:
#张量连接
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2,1]])
#沿着行，沿着列
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [13]:
#逻辑运算
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [14]:
#对张量内所有元素求和
X.sum()

tensor(66.)

In [15]:
#广播机制
#让形状不同的张量进行运算
#1.通过适当复制元素来扩展一个或两个元素
#2.对生成的数组执行元素操作
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a,b


(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [16]:
#a 为3*1 要变成3*2 复制列
#b 为1*2 要变成3*2 复制行
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [17]:
 X,X[-1],X[1,2]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor(6.))

In [21]:
#赋值
X[1, 2] = 9
#为多元素赋值
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [28]:
#利用切边节省内存，让参数原地更新
#传统形式
before = id(Y)
Y = Y + X
print("两者内存地址是否相同",id(Y) == before)

Z = torch.zeros_like(Y)
print('id(Z)',id(Z))
Z[:] = X + Y
print('id(Z)',id(Z))
#使用X[:] = X + Y或X += Y来减少操作的内存开销。

两者内存地址是否相同 False
id(Z) 1807433764432
id(Z) 1807433764432


In [31]:
#转化为其他Python对象
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)
# 要将大小为1的张量转换为Python标量，我们可以调用item函数或Python的内置函数。
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)