In [1]:
#标量：仅包含一个数值
import torch
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [25]:
#向量：可视为标量值组成的列表。这些标量值被称为向量的元素或分量 粗体小写符号
# 一般默认为列向量
x = torch.arange(4)
print('我是向量',x)
#向量的长度，即其中元素的数量
print('x的长度:',len(x))
#。形状（shape）是一个元素组，列出了张量沿每个轴的长度（维数）。
print('x的形状',x.shape)
#向量或轴的维度表示向量或轴的长度，即向量或轴的元素数量
#张量的维度用来表示张量具有的轴数。在这个意义上，张量的某个轴的维数就是这个轴的长度。

我是向量 tensor([0, 1, 2, 3])
x的长度: 4
x的形状 torch.Size([4])


In [8]:
#矩阵：具有两个轴的张量，通常用粗体、大写字母来表示
A = torch.arange(20).reshape(5, 4)
print('我是矩阵',A)
print('我是A的转置',A.T)

我是矩阵 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
我是A的转置 tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


In [12]:
#张量算法的基本性质
#1.执行元素上的运算
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # 通过分配新内存，将A的一个副本分配给B
print(A, A + B, A * B)
#将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]]) tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])


(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [12]:
#张量算法的基本性质
#1.执行元素上的运算
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # 通过分配新内存，将A的一个副本分配给B
print(A, A + B, A * B)
#将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]]) tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]]) tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])


(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

In [23]:
#降维
print("我是A\n",A)
print('我的形状：',A.shape)
print('降维求和',A.sum())
print('沿0轴或y轴求和',A.sum(axis=0))
print('沿1轴或x轴求和',A.sum(axis=1))
print('获取张量内元素的个数：',A.numel())
#非降维求和
print('非降维求和\n',A.sum(axis=1, keepdims=True))
print('想沿0轴计算A元素的累积总和\n',A.cumsum(axis=0)
)

我是A
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
我的形状： torch.Size([5, 4])
降维求和 tensor(190.)
沿0轴或y轴求和 tensor([40., 45., 50., 55.])
沿1轴或x轴求和 tensor([ 6., 22., 38., 54., 70.])
获取张量内元素的个数： 20
非降维求和
 tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
想沿0轴计算A元素的累积总和
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])


In [36]:
# 矩阵-向量积
x = torch.arange(4)
A = torch.arange(20).reshape(5, 4)
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14,  38,  62,  86, 110]))

In [23]:
#降维
print("我是A\n",A)
print('我的形状：',A.shape)
print('降维求和',A.sum())
print('沿0轴或y轴求和',A.sum(axis=0))
print('沿1轴或x轴求和',A.sum(axis=1))
print('获取张量内元素的个数：',A.numel())
#非降维求和
print('非降维求和\n',A.sum(axis=1, keepdims=True))
print('想沿0轴计算A元素的累积总和\n',A.cumsum(axis=0)
)

我是A
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
我的形状： torch.Size([5, 4])
降维求和 tensor(190.)
沿0轴或y轴求和 tensor([40., 45., 50., 55.])
沿1轴或x轴求和 tensor([ 6., 22., 38., 54., 70.])
获取张量内元素的个数： 20
非降维求和
 tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
想沿0轴计算A元素的累积总和
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])


In [23]:
#降维
print("我是A\n",A)
print('我的形状：',A.shape)
print('降维求和',A.sum())
print('沿0轴或y轴求和',A.sum(axis=0))
print('沿1轴或x轴求和',A.sum(axis=1))
print('获取张量内元素的个数：',A.numel())
#非降维求和
print('非降维求和\n',A.sum(axis=1, keepdims=True))
print('想沿0轴计算A元素的累积总和\n',A.cumsum(axis=0)
)

我是A
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
我的形状： torch.Size([5, 4])
降维求和 tensor(190.)
沿0轴或y轴求和 tensor([40., 45., 50., 55.])
沿1轴或x轴求和 tensor([ 6., 22., 38., 54., 70.])
获取张量内元素的个数： 20
非降维求和
 tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
想沿0轴计算A元素的累积总和
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])


In [23]:
#降维
print("我是A\n",A)
print('我的形状：',A.shape)
print('降维求和',A.sum())
print('沿0轴或y轴求和',A.sum(axis=0))
print('沿1轴或x轴求和',A.sum(axis=1))
print('获取张量内元素的个数：',A.numel())
#非降维求和
print('非降维求和\n',A.sum(axis=1, keepdims=True))
print('想沿0轴计算A元素的累积总和\n',A.cumsum(axis=0)
)

我是A
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
我的形状： torch.Size([5, 4])
降维求和 tensor(190.)
沿0轴或y轴求和 tensor([40., 45., 50., 55.])
沿1轴或x轴求和 tensor([ 6., 22., 38., 54., 70.])
获取张量内元素的个数： 20
非降维求和
 tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
想沿0轴计算A元素的累积总和
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])


In [23]:
#降维
print("我是A\n",A)
print('我的形状：',A.shape)
print('降维求和',A.sum())
print('沿0轴或y轴求和',A.sum(axis=0))
print('沿1轴或x轴求和',A.sum(axis=1))
print('获取张量内元素的个数：',A.numel())
#非降维求和
print('非降维求和\n',A.sum(axis=1, keepdims=True))
print('想沿0轴计算A元素的累积总和\n',A.cumsum(axis=0)
)

我是A
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
我的形状： torch.Size([5, 4])
降维求和 tensor(190.)
沿0轴或y轴求和 tensor([40., 45., 50., 55.])
沿1轴或x轴求和 tensor([ 6., 22., 38., 54., 70.])
获取张量内元素的个数： 20
非降维求和
 tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
想沿0轴计算A元素的累积总和
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])


In [23]:
#降维
print("我是A\n",A)
print('我的形状：',A.shape)
print('降维求和',A.sum())
print('沿0轴或y轴求和',A.sum(axis=0))
print('沿1轴或x轴求和',A.sum(axis=1))
print('获取张量内元素的个数：',A.numel())
#非降维求和
print('非降维求和\n',A.sum(axis=1, keepdims=True))
print('想沿0轴计算A元素的累积总和\n',A.cumsum(axis=0)
)

我是A
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
我的形状： torch.Size([5, 4])
降维求和 tensor(190.)
沿0轴或y轴求和 tensor([40., 45., 50., 55.])
沿1轴或x轴求和 tensor([ 6., 22., 38., 54., 70.])
获取张量内元素的个数： 20
非降维求和
 tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
想沿0轴计算A元素的累积总和
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])


In [23]:
#降维
print("我是A\n",A)
print('我的形状：',A.shape)
print('降维求和',A.sum())
print('沿0轴或y轴求和',A.sum(axis=0))
print('沿1轴或x轴求和',A.sum(axis=1))
print('获取张量内元素的个数：',A.numel())
#非降维求和
print('非降维求和\n',A.sum(axis=1, keepdims=True))
print('想沿0轴计算A元素的累积总和\n',A.cumsum(axis=0)
)

我是A
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])
我的形状： torch.Size([5, 4])
降维求和 tensor(190.)
沿0轴或y轴求和 tensor([40., 45., 50., 55.])
沿1轴或x轴求和 tensor([ 6., 22., 38., 54., 70.])
获取张量内元素的个数： 20
非降维求和
 tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])
想沿0轴计算A元素的累积总和
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])


In [ ]:
#范数(norm):向量的范数是表示一个向量有多大。这里考虑的大小（size）概念不涉及维度，而是分量的大小。
#L2范数：向量元素平方和的平方根
u = torch.tensor([3.0, -4.0])
torch.norm(u)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
#L1范数：表示为向量元素的绝对值之和
torch.abs(u).sum()
#矩阵的Frobenius范数：是矩阵元素平方和的平方根
torch.norm(torch.ones((4, 9)))
#范数与目标函数息息相关，用向量表示物品（如单词、产品或新闻文章），以便最小化相似项目之间的距离，最大化不同项目之间的距离