In [15]:
import torch

In [16]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [17]:
x.requires_grad_(True)#存储梯度

tensor([0., 1., 2., 3.], requires_grad=True)

In [23]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [24]:
#反向传播函数来自动计算y关于x每个分量的梯度
y.backward()
x.grad

tensor([ 0., 12., 24., 36.])

In [26]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])